services:
  postgres:
    container_name: postgres-sql
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lamis_database
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - lamis-network
  spring-boot-app:
    container_name: lamis-core
    image: lamis_new_core
    ports:
      - "8080:8080"
    networks:
      - spring-boot-network
volumes:
  postgres:
networks:
  spring-boot-network:
    driver: bridge
  lamis-network:
    driver: bridge